### ISSUE TITLE
<reified> klass is not constructor 

### ISSUE THREAD

**Issue by dwelch2344** [rezonant/phantomdi#1]
Following along with the first example but can't get it to run. Guessing it has to do with providing a concrete class, or the fact that I'm running `phantomdi@0.0.3` with `typescript-rtti@0.4.14` and both are pretty fresh :) 

The following test + stacktrace is what I'm getting: 

```ts
import 'reflect-metadata'
import { injector, provide } from 'phantomdi/dist/injector';
import { reify } from 'typescript-rtti';

interface Foobar { 
    version : number;
}

class A {

    constructor(readonly foobar : Foobar) {

    }

    get version() { return this.foobar.version; }
}

test('thing', async () => {
  // @ts-ignore
  const provider1 = provide(reify<Foobar>(), { version: 123 })
  const provider2 = provide(A)
  const a = injector([ provider1, provider2 ]).provide(A)
  console.log(a)
})
```

```
 FAIL  src/injector.test.ts
  ✕ thing (2 ms)

  ● thing

    TypeError: klass is not a constructor

      at Injector.construct (node_modules/phantomdi/src/injector.ts:107:6)
      at __RΦ.f.__RΦ.m.n (node_modules/phantomdi/src/injector.ts:44:36)
      at Injector.invoke (node_modules/phantomdi/src/injector.ts:94:25)
      at Injector.provide (node_modules/phantomdi/src/injector.ts:82:29)
      at dep.tokens.map.__RΦ.f.__RΦ.m.n (node_modules/phantomdi/src/injector.ts:155:44)
          at Array.map (<anonymous>)
      at node_modules/phantomdi/src/injector.ts:155:33
      at Injector.invoke (node_modules/phantomdi/src/injector.ts:94:25)
      at Injector.resolve (node_modules/phantomdi/src/injector.ts:155:24)
      at klass.analyze.map.__RΦ.f.__RΦ.m.n (node_modules/phantomdi/src/injector.ts:107:6)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.109 s
```

Toying around, making a tweak to `injector.ts` from 
```ts
   // ...
   construct<T>(klass : Constructor<T>): T {
        return new klass(...this.analyze(klass).map(d => this.resolve(d)));
    }
    // ...
```
to
```
    // ...
    construct<T>(klass : Constructor<T>): T {
        if( klass instanceof Function ){
          return new klass(...this.analyze(klass).map(d => this.resolve(d)));
        }else {
          return klass
        }
    }
    // ...
```
seems to fix my wagon.. but I'm sure there's something more robust / cleaner you've got cooking.

**Comment by dwelch2344** [comment]
Ended up using jest to crank out a small test based on all the use cases in the README and everything seems to play nice with this change. Next step is to actually clone the repo and figure out your test harness / etc :) 

Sharing here in the meantime: 
```ts
import 'reflect-metadata'
import { injector, provide, alter } from 'phantomdi/dist/injector';
import { reify } from 'typescript-rtti';

test('interfaces', async () => {
  interface Foobar { 
      version : number;
  }

  class A {

      constructor(readonly foobar : Foobar) {

      }

      get version() { return this.foobar.version; }
  }
  // @ts-ignore
  const provider1 = provide(reify<Foobar>(), { version: 123 })
  const provider2 = provide(A)
  const a = injector([ provider1, provider2 ]).provide(A)
  expect(a.version).toBe(123);
})

test('functions', async () => {
  class A { foo = 123 }
  class B { bar = 321 }

  function foobar(a : A, b : B) {
      return a.foo + b.bar;
  }

  expect(injector([ provide(A), provide(B) ]).invoke(globalThis, foobar))
      .toBe(123 + 321);
})



test('optional', async () => {
  class A { foo = 123 }
  class B { bar = 321 }
  
  function foobar(a : A, b? : B) {
      return a.foo + (b?.bar ?? 555);
  }
  
  expect(injector([ provide(A) ]).invoke(globalThis, foobar))
      .toBe(123 + 555);
})
test('initializers', async () => {
  class A { foo= 123 }
  class B { constructor(public bar = 321){} }
  
  function foobar(a : A, b = new B(555)) {
      return a.foo + (b?.bar);
  }
  
  expect(injector([ provide(A) ]).invoke(globalThis, foobar))
      .toBe(123 + 555);
})
test('Heirarchical', async () => {

  class A { 
    constructor(readonly foo = 123) {
    }
  }

  class B {
      bar = 321;
  }

  let parent = injector([ provide(A), provide(B) ]);
  let container = injector([ provide(A, () => new A(555))], parent)

  expect(container.provide(A).foo).toBe(555);
  expect(container.provide(B).bar).toBe(321);
})
test('Alterations', async () => {

  class A {
    bar = 123;
    foo() {
        return 'original';
    }
  }

  let i = injector([ provide(A), alter(A, {
      beforeFoo() {
          console.log(`foo() is about to run`);
      },

      afterFoo() {
          console.log(`foo() is finished running`);
      },
      aroundFoo(foo : () => string) {
          return () => {
              console.log('around before')
              const result = `around(${foo.call(this)})`
              console.log('around after:', result)
              return result
          }
      }

  })]);

  let a = i.provide(A);

  expect(a.bar).toBe(123);
  expect(a.foo()).toBe('around(original)');
})
```

**Comment by rezonant** [comment]
The provider (arg 2 of `provide()`) is a function, so:

```
const provider1 = provide(reify<Foobar>(), () => { version: 123 })

**Comment by rezonant** [comment]
Replicating in the codebase I get:

![image](https://user-images.githubusercontent.com/409140/157390382-eaea0351-1fc5-4e2b-9e10-8073fe774daf.png)

Versus:
![image](https://user-images.githubusercontent.com/409140/157390533-b06e4842-b26f-4e76-8a8d-0bd61e769fb9.png)

Yields:

![image](https://user-images.githubusercontent.com/409140/157390562-117ccff6-7e48-4766-845f-035a6990af36.png)

**Comment by rezonant** [comment]
I do think we should catch unconstructible and throw with a nice error message describing the issue here

**Comment by rezonant** [comment]
OK I think this works, David let me know if you still see an issue

**Comment by rezonant** [comment]
> Next step is to actually clone the repo and figure out your test harness / etc :)

Test harness is easy-- its just Razmin, run `npm test` to run the test suite. It's basically just `describe/it` style

**Comment by rezonant** [comment]
The trick of providers in this lib is to realize there is only two types: Functions that provide a value (which are run via the injector, so their args are injected) or constructors (ie `new x()` works). Everything else is built on that

**Comment by rezonant** [comment]
Doh, yeah the readme led you astray here.

**Comment by dwelch2344** [comment]
No worries on the README. Yeah, a little cleanup (which you may have done) as things have evolved is all it looks like :) 

Loving this so far! Does the constructor method work with other deps that will be found in the injector/parents? I.e.  `new x(a: A)` will also be injected?

**Comment by rezonant** [comment]
Oh so you mean A and B is provided, X depends on A and B, but X is not provided, then you do injector.provide(X), will it work or say no provider for X?

If you use injector.provide(X) it will say no provider, but for that you would use injector.construct(X) and it would work fine. This is consistent with how you inject the args of a function-- if you did injector.provide((a : A) => 123) it would use that function as the injection token, and of course a provider wouldn't be available for that. You would instead use injector.invoke() which would give the desired result.

**Comment by rezonant** [comment]
Or if you mean will it fulfill subdependencies like if A depended on B depended on C and B and C are provided, yes it does that

**Comment by dwelch2344** [comment]
Rad! This is suuuuper great :) 

Just confirmed the DX. Thanks for quick turn around
